name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run shellcheck
        run: shellcheck dev
      - name: Test version output without ddev
        run: |
          chmod +x dev
          # Temporär die ddev-Prüfung deaktivieren für den Versionstest
          sed -i 's/command -v ddev/false/' dev
          ./dev --version
