name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          # Install Bats testing framework
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          sudo ./install.sh /usr/local
          cd ..
          # Install Bats support libraries
          git clone https://github.com/bats-core/bats-support.git
          git clone https://github.com/bats-core/bats-assert.git

      - name: Check script permissions
        run: |
          test -x src/dev || chmod +x src/dev
          chmod +x tests/mocks/ddev

      - name: Run shellcheck
        run: shellcheck src/dev

      - name: Test version output
        run: ./src/dev --version

      - name: Check script syntax
        run: bash -n src/dev

      - name: Run Bats unit tests
        run: bats tests/unit/

      - name: Run Bats integration tests
        run: |
          # Skip integration tests for now as they require complex DDEV setup
          echo "Integration tests skipped in CI - require full DDEV environment"
          # bats tests/integration/

      - name: Validate documentation
        run: |
          test -f README.md
          test -f READMEDE.md
          test -f CONTRIBUTING.md
          test -f LICENSE
          test -f CHANGELOG.md

      - name: Check file encoding
        run: |
          if file src/dev | grep -q "CRLF"; then
            echo "Error: CRLF line endings detected"
            exit 1
          fi
